CUDA_VISIBLE_DEVICES=0 \
python -m scripts.train_fno_ns_contextual \
    --data_path ../data/ns_contextual/ns_random_forces_top100_mu.h5 \
    --test_data_path ../data/ns_contextual/ns_random_forces_top100_mu.h5 ../data/ns_contextual/ns_random_forces_top100_mu_k_4.h5 ../data/ns_contextual/ns_random_forces_bottom100_mu.h5\
    --data_name NS_Contextual_Fewshot_test \
    --n_train 100 \
    --n_test 100 \
    --batch_size 64 \
    --train_subsample_rate 4 \
    --test_subsample_rate 4 \
    --time_step 10 \
    --n_modes 21 \
    --num_prod 2 \
    --n_layers 4 \
    --pos_encoding True \
    --hidden_channels 32 \
    --lifting_channels 256 \
    --projection_channels 64 \
    --factorization tucker \
    --rank 0.42 \
    --lr 1e-3 \
    --weight_decay 1e-4 \
    --scheduler_steps 100 \
    --scheduler_gamma 0.5 \
    --train_loss h1 \
    --time_suffix True \
    --config_details True \
    --log_interval 4 \
    --save_interval 20 \
    --epochs 500 \
    --verbose True \
    --random_seed False \
    --seed 0 \
    --simaug_train_data True \
    --simaug_test_data True \
    --channel_mixing mlp \