CUDA_VISIBLE_DEVICES=0 \
python -m scripts.train_fno_ns_contextual \
    --data_path ../../data/ns_contextual/ns_random_forces_top200_mu.h5 \
    --test_data_path ../../data/ns_contextual/ns_random_forces_top200_mu.h5 ../../data/ns_contextual/ns_random_forces_bottom100_mu.h5\
    --data_name NS_Contextual_Fewshot \
    --n_train 100 \
    --n_test 100 \
    --batch_size 64 \
    --train_subsample_rate 4 \
    --test_subsample_rate 4 \
    --time_step 10 \
    --n_modes 21 \
    --num_prod 2 \
    --n_layers 2 \
    --pos_encoding 1 \
    --hidden_channels 32 \
    --lifting_channels 256 \
    --projection_channels 64 \
    --factorization tucker \
    --rank 0.42 \
    --lr 1e-3 \
    --weight_decay 1e-4 \
    --scheduler_steps 100 \
    --scheduler_gamma 0.5 \
    --train_loss h1 \
    --time_suffix 1 \
    --config_details 1 \
    --log_interval 4 \
    --save_interval 20 \
    --epochs 500 \
    --verbose 1 \
    --random_seed 0 \
    --seed 0 \
    --simaug_train_data 0 \
    --simaug_test_data 1 \
    # --channel_mixing prod-layer \